apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: pingpong-app-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: pingpong-app
    spec:
      containers:
      - name: 
        image: test-refactory
        ports:
        - containerPort: 80
