apiVersion: v1
kind: Service
metadata:
  name: pingpong-app-service
spec:
  selector:
    app: pingpong-app
  type: LoadBalancer
  ports:
    - name: pingpong-app-port
      port: 8080
      targetPort: 80
